PortalSpolecznosciowy/Controllers/ContactsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    public class ContactsController : Controller
    {

        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();

        [SessionExistFilter]
        public ActionResult Index()
        {
            IEnumerable<Contacts> contactList = DB.Contacts.OrderByDescending(x => x.Active).ToList();
            return View(contactList);
        }

        [SessionExistFilter]
        public ActionResult AcceptReqest(int id)
        {
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            contact.Active = 2;
            DB.SaveChanges();
            return RedirectToAction("Index", "MainPanel");
        }

        [SessionExistFilter]
        public ActionResult DeclineReqest(int id)
        {
            
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            DB.Contacts.Remove(contact);
            DB.SaveChanges();
            
            /*
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            contact.Active = 0;
            DB.SaveChanges();
            */
            return RedirectToAction("Index", "MainPanel");
        }

        [SessionExistFilter]
        public ActionResult DeleteContact(int id)
        {
            
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            DB.Contacts.Remove(contact);
            DB.SaveChanges();
            
            /*
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            contact.Active = 0;
            DB.SaveChanges();
            */
            return RedirectToAction("Index", "MainPanel");
        }

    }
}

PortalSpolecznosciowy/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Models;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    public class UsersController : Controller
    {
        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();
        private int PageSize = 10;

        public ActionResult Index()
        {
            List<Users> userList = DB.Users.ToList();
            return View(userList);
        }

        public ActionResult UserProfile(int page = 1)
        {
            string userLogin = HttpContext.Request.Params.Get("userLogin");
            if (string.IsNullOrEmpty(userLogin))
            {
                return RedirectToAction("Index");
            }
            try
            {
                int myId = 0;
                if (Session["Login"] != null)
                {
                    string myLogin = Session["Login"].ToString();
                    myId = DB.Users.Single(x => x.Login == myLogin).ID;
                }

                int friendId = DB.Users.Single(x => x.Login == userLogin).ID;

                bool existFriend = DB.Contacts.Any(x =>
                    (x.UserId1 == myId || x.UserId2 == myId) &&
                    (x.UserId1 == friendId || x.UserId2 == friendId));

                byte friendStatus = 0;

                if (existFriend && (myId != friendId))
                {
                    friendStatus = DB.Contacts.Single(x =>
                        (x.UserId1 == myId || x.UserId2 == myId) &&
                        (x.UserId1 == friendId || x.UserId2 == friendId)).Active;
                }

                UserProfile up = new UserProfile
                {
                    UserLogin = userLogin,
                    ProfileImageUrl = DB.Users.Single(x => x.Login == userLogin).Profil_image,
                    Role = DB.Users.Single(x => x.Login == userLogin).Role,

                    ArticleList = DB.Articles
                        .Where(x => x.Users.Login == userLogin)
                        .OrderByDescending(art => art.Date)
                        .Skip((page - 1)*PageSize)
                        .Take(PageSize)
                        .ToList(),

                    FriendStatus = friendStatus,

                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = DB.Articles.Count(x => x.Users.Login == userLogin)
                    },

                    UserContacts =
                        DB.Contacts.Where(x => x.UserId1 == friendId || x.UserId2 == friendId)
                            .OrderBy(x => x.Active)
                            .ToList()
                };

                return View(up);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult GetUsers(string query)
        {
            var results = from N in DB.Users
                          where N.Login.StartsWith(query)
                          select new { N.Login };
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        [SessionExistFilter]
        public ActionResult AddContact(string friendLogin)
        {
            string myLogin = Session["Login"].ToString();

            Contacts contact = new Contacts
            {
                UserId1 = DB.Users.Single(x => x.Login == myLogin).ID,
                UserId2 = DB.Users.Single(x => x.Login == friendLogin).ID,
                Active = 1
            };

            DB.Contacts.Add(contact);
            DB.SaveChanges();
            return RedirectToAction("UserProfile", new { userLogin = friendLogin });
        }

        [SessionExistFilter]
        public ActionResult ChangeRole( UserProfile ur )
        {
            Users user = DB.Users.Single(x => x.Login == ur.UserLogin);
            user.Role = ur.Role;
            DB.SaveChanges();
            return RedirectToAction("UserProfile", new { userLogin = ur.UserLogin});
        }

    }
}

PortalSpolecznosciowy/Views/Contacts/Index.cshtml
@model IEnumerable<PortalSpolecznosciowy.Repository.Contacts>

@{
    ViewBag.Title = "Moje Kontakty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Moje Kontakty</h2>
<table class="table">
   
    @foreach (var item in Model)
    {
        if (item.Active == 0) { continue; }
        var user1 = new PortalSpolecznosciowy.Repository.GetUser(item.UserId1).UserLogin;
        var user2 = new PortalSpolecznosciowy.Repository.GetUser(item.UserId2).UserLogin;
        if (user1 != Session["Login"].ToString() && user2 != Session["Login"].ToString()) { continue; }
        <tr>
            <td>
                @{
                    @(user1 == Session["Login"].ToString() ?
                        Html.ActionLink(user2, "UserProfile", "Users", new { userLogin = user2 }, null)
                        : Html.ActionLink(user1, "UserProfile", "Users", new { userLogin = user1 }, null))
                }
            </td>

            <td>
                @switch (item.Active)
                {
                    /*
                    case 0: //niezjajomi ?? nie powinno tutaj sie to wgl pojawic
                        {
                            break;
                        }
                    */

                    case 1: //oczekujacy na akceptacje
                        {
                            @Html.Raw("(Oczekujące) <td>")
                            if (user1 != Session["Login"].ToString())
                            {
                                @Html.ActionLink("Akceptuj", "AcceptReqest", "Contacts", new { id = item.Id })
                                @Html.Raw(" | ")
                                @Html.ActionLink("Odrzuć", "DeclineReqest", "Contacts", new { id = item.Id })
                            }
                            @Html.Raw("</td>")
                            break;
                        }

                    case 2: //znajomi
                        {
                            @Html.Raw("<td>")

                            @Html.ActionLink("Usuń znajomego", "DeleteContact", "Contacts", new { id = item.Id })

                            @Html.Raw("</td>")
                            break;
                        }
                }
            </td>
        </tr>
    }
</table>