PortalSpolecznosciowy/Models/UserProfile.cs
using System.Collections.Generic;
using System.Web;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Models
{
    public class UserProfile
    {
        public string UserLogin { get; set; }
        public string ProfileImageUrl { get; set; }
        public List<Articles> ArticleList { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CommentContent { set; get; }
        public HttpPostedFileBase File { get; set; }
        //public Comments comments { get; set; }
        public byte FriendStatus { get; set; }
        public int Role { get; set; }

        public IEnumerable<Contacts> UserContacts { get; set; } 
    }
}

PortalSpolecznosciowy/Controllers/ArticleController.cs
using System;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Models;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    public class ArticleController : Controller
    {
        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();

        // GET: Article
        public ActionResult Index(int? articleId)
        {
            if (Session["Login"] != null && articleId != null)
            {
                string userLogin = Session["Login"].ToString();
                ArticleAndComments AaC = new ArticleAndComments
                {
                    Article = DB.Articles.Single(x => x.ID == articleId),
                    Comments = DB.Comments.Where(x => x.Article_ID == articleId).OrderBy(x => x.Date),
                    UserLogin = userLogin
                };
                return View(AaC);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult AddComment(ArticleAndComments aac)
        {
            if (aac.CommentContent == null && aac.File == null)
            {
                TempData["error"] = "Musisz napisać komentarz lub dodać obrazek";
                return RedirectToAction("Index", new { articleId = aac.ArticleID} );
            }

            Comments com = new Comments
            {
                Users_ID = DB.Users.Single(x => x.Login == aac.UserLogin).ID,
                Article_ID = aac.ArticleID,
                Date = DateTime.Now,
                Accessible = DB.Articles.Single(x => x.ID == aac.ArticleID).Accessible,
                Content = aac.CommentContent,
                Image = null,
            };

            DB.Comments.Add(com);
            DB.SaveChanges();

            if (aac.File != null && aac.File.ContentLength > 0)
            {
                try
                {
                    string extension = Path.GetExtension(aac.File.FileName).ToLower();
                    if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                    {
                        Image image = Image.FromStream(aac.File.InputStream, true, true);
                        string path = @"~/CommentImages/" + com.ID + ".jpeg";
                        image.Save(Server.MapPath(path), System.Drawing.Imaging.ImageFormat.Jpeg);
                        com.Image = path;
                        DB.Comments.AddOrUpdate(com);
                        DB.SaveChanges();
                    }
                    else
                    {
                        throw new Exception("To nie jest obrazek!");
                    }
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Błąd: " + ex.Message;
                    return RedirectToAction("Index");
                }
            }
            
            return RedirectToAction("Index", new { articleId = com.Article_ID });
        }

        [SessionExistFilter]
        public ActionResult EditArticle(int artId)
        {
            Articles art = DB.Articles.Single(x => x.ID == artId);
            EditArticle editArt = new EditArticle
            {
                ID = art.ID,
                Content = art.Content,
                Users_ID = art.Users_ID,
                Date = art.Date,
                Accessible = art.Accessible,
                ImagePath = art.Image
            };
            return View(editArt);
        }

        [SessionExistFilter]
        public ActionResult SaveEditArticle(EditArticle artModel)
        {
            Articles art = DB.Articles.Single(x => x.ID == artModel.ID);
            art.Content = artModel.Content;
            art.Date = DateTime.Now;
            if (artModel.Image)
            {
                string pathToFile = Server.MapPath(art.Image);
                System.IO.File.Delete(pathToFile);
                art.Image = String.Empty;
            }

            DB.SaveChanges();
            return RedirectToAction("Index", new { articleId = artModel.ID });
        }

        [SessionExistFilter]
        public ActionResult DeleteArticle(int artId, int authorId)
        {
            Articles art = DB.Articles.Single(x => x.ID == artId);

            if (!String.IsNullOrEmpty(art.Image))
            {
                string pathToFile = Server.MapPath(art.Image);
                System.IO.File.Delete(pathToFile);
            }

            DB.Articles.Remove(art);
            DB.SaveChanges();
            return RedirectToAction("UserProfile", "Users", new {userLogin = new GetUser(authorId).UserLogin });
        }

        [SessionExistFilter]
        public ActionResult DeleteComment(int artId, int comId)
        {
            Comments comment = DB.Comments.Single(x => x.ID == comId);

            if (!String.IsNullOrEmpty(comment.Image))
            {
                string pathToFile = Server.MapPath(comment.Image);
                System.IO.File.Delete(pathToFile);
            }
                
            DB.Comments.Remove(comment);
            DB.SaveChanges();
            return RedirectToAction("Index", new { articleId = artId });
        }

    }
}

PortalSpolecznosciowy/Controllers/ContactsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    public class ContactsController : Controller
    {

        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();

        [SessionExistFilter]
        public ActionResult Index()
        {
            IEnumerable<Contacts> contactList = DB.Contacts.OrderByDescending(x => x.Active).ToList();
            return View(contactList);
        }

        [SessionExistFilter]
        public ActionResult AcceptReqest(int id)
        {
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            contact.Active = 2;
            DB.SaveChanges();
            return RedirectToAction("Index", "MainPanel");
        }

        [SessionExistFilter]
        public ActionResult DeclineReqest(int id)
        {
            
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            DB.Contacts.Remove(contact);
            DB.SaveChanges();
            
            /*
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            contact.Active = 0;
            DB.SaveChanges();
            */
            return RedirectToAction("Index", "MainPanel");
        }

        [SessionExistFilter]
        public ActionResult DeleteContact(int id)
        {
            
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            DB.Contacts.Remove(contact);
            DB.SaveChanges();
            
            /*
            Contacts contact = DB.Contacts.Single(x => x.Id == id);
            contact.Active = 0;
            DB.SaveChanges();
            */
            return RedirectToAction("Index", "MainPanel");
        }

    }
}

PortalSpolecznosciowy/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Models;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    public class UsersController : Controller
    {
        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();
        private int PageSize = 10;

        public ActionResult Index()
        {
            List<Users> userList = DB.Users.ToList();
            return View(userList);
        }

        public ActionResult UserProfile(int page = 1)
        {
            string userLogin = HttpContext.Request.Params.Get("userLogin");
            if (string.IsNullOrEmpty(userLogin))
            {
                return RedirectToAction("Index");
            }
            try
            {
                int myId = 0;
                if (Session["Login"] != null)
                {
                    string myLogin = Session["Login"].ToString();
                    myId = DB.Users.Single(x => x.Login == myLogin).ID;
                }

                int friendId = DB.Users.Single(x => x.Login == userLogin).ID;

                bool existFriend = DB.Contacts.Any(x =>
                    (x.UserId1 == myId || x.UserId2 == myId) &&
                    (x.UserId1 == friendId || x.UserId2 == friendId));

                byte friendStatus = 0;

                if (existFriend && (myId != friendId))
                {
                    friendStatus = DB.Contacts.Single(x =>
                        (x.UserId1 == myId || x.UserId2 == myId) &&
                        (x.UserId1 == friendId || x.UserId2 == friendId)).Active;
                }

                UserProfile up = new UserProfile
                {
                    UserLogin = userLogin,
                    ProfileImageUrl = DB.Users.Single(x => x.Login == userLogin).Profil_image,
                    Role = DB.Users.Single(x => x.Login == userLogin).Role,

                    ArticleList = DB.Articles
                        .Where(x => x.Users.Login == userLogin)
                        .OrderByDescending(art => art.Date)
                        .Skip((page - 1)*PageSize)
                        .Take(PageSize)
                        .ToList(),

                    FriendStatus = friendStatus,

                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = DB.Articles.Count(x => x.Users.Login == userLogin)
                    },

                    UserContacts =
                        DB.Contacts.Where(x => x.UserId1 == friendId || x.UserId2 == friendId)
                            .OrderBy(x => x.Active)
                            .ToList()
                };

                return View(up);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult GetUsers(string query)
        {
            var results = from N in DB.Users
                          where N.Login.StartsWith(query)
                          select new { N.Login };
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        [SessionExistFilter]
        public ActionResult AddContact(string friendLogin)
        {
            string myLogin = Session["Login"].ToString();

            Contacts contact = new Contacts
            {
                UserId1 = DB.Users.Single(x => x.Login == myLogin).ID,
                UserId2 = DB.Users.Single(x => x.Login == friendLogin).ID,
                Active = 1
            };

            DB.Contacts.Add(contact);
            DB.SaveChanges();
            return RedirectToAction("UserProfile", new { userLogin = friendLogin });
        }

        [SessionExistFilter]
        public ActionResult ChangeRole( UserProfile ur )
        {
            Users user = DB.Users.Single(x => x.Login == ur.UserLogin);
            user.Role = ur.Role;
            DB.SaveChanges();
            return RedirectToAction("UserProfile", new { userLogin = ur.UserLogin});
        }

    }
}

PortalSpolecznosciowy/Views/Users/Index.cshtml
@using PortalSpolecznosciowy.Repository
@{
    ViewBag.Title = "Lista użytkowników";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Users> userList = ViewData.Model;
}

<h2>Lista użytkowników</h2>

@foreach (var user in userList)
{
    <p>
        @Html.ActionLink(@user.Login, "UserProfile", new { userLogin = @user.Login }, null)
    </p>
}

PortalSpolecznosciowy/Views/Users/UserProfile.cshtml
@model PortalSpolecznosciowy.Models.UserProfile

@{
    ViewBag.Title = "Profil użytkownika";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.UserLogin</h2>

<div class="row panel" style="margin-top: 50px;">
    <div class="col-md-3">
        <a class="group3" href="@Url.Content(@Model.ProfileImageUrl)" title="@Model.UserLogin">
            <img src="@Url.Content(@Model.ProfileImageUrl)" width="200" height="200" alt="ProfileImage"/>
        </a>
        <br/>
        <br/>
        @if (Session["Login"] != null)
        {
            if (new PortalSpolecznosciowy.Repository.GetUser(Session["Login"].ToString()).UserID !=
                new PortalSpolecznosciowy.Repository.GetUser(@Model.UserLogin).UserID)
            {
                switch (Model.FriendStatus)
                {
                    case 0:
                    {
                        //jeżeli nie ma znajomego
                        @Html.ActionLink("Dodaj znajomego", "AddContact", "Users", new {friendLogin = @Model.UserLogin}, new {@class = "btn btn-primary", @style = "color:white"})
                        break;
                    }

                    case 1:
                    {
                        //czeka na akceptacje
                        @Html.ActionLink("Czeka na akceptacje", "Index", "Contacts", null, new {@class = "btn btn-info", @style = "color:white"})
                        break;
                    }

                    case 2:
                    {
                        //sa znajomymi
                        @Html.ActionLink("Znajomy", "Index", "Contacts", null, new {@class = "btn btn-success", @style = "color:white"})
                        break;
                    }
                }
            }
            <br/>
            <br/>
            <br/>
            <br/>

            if (new PortalSpolecznosciowy.Repository.GetRole(Session["Login"].ToString()).Role == 3)
            {
                List<SelectListItem> listItems = new List<SelectListItem>();
                listItems.Add(new SelectListItem
                {
                    Text = "Użytkownik",
                    Value = "1"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "Moderator",
                    Value = "2"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "Administrator",
                    Value = "3"
                });

                using (Html.BeginForm("ChangeRole", "Users", FormMethod.Post))
                {
                    @Html.DropDownListFor(x => x.Role, new SelectList(listItems, "Value", "Text", @Model.Role), new {@class = "btn btn-primary dropdown-toggle"})
                    @Html.HiddenFor(x => x.UserLogin, @Model.UserLogin)
                    <br/>
                    <br/>
                    <input type="submit" value="Zmień uprawnienia" class="btn " style="color: brown"/>
                }
            }
        }
        <br/>
    </div>
    <div id="categories" class="col-md-5">

        @foreach (var art in Model.ArticleList)
        {
            var user = new PortalSpolecznosciowy.Repository.GetUser(@art.Users_ID).UserLogin;
            @Html.Raw("<div class=\"panel panel-default\">")
            @Html.Raw("<div class=\"panel-body\">")
            <label class="h6">
                @Html.Raw("<b> autor: " + @user + "</b>") <br/>
            </label>

            if (Session["Login"] != null && (new PortalSpolecznosciowy.Repository.GetRole(Session["Login"].ToString()).Role == 2 ||
                                             new PortalSpolecznosciowy.Repository.GetRole(Session["Login"].ToString()).Role == 3))
            {
                @Html.ActionLink("Edytuj", "EditArticle", "Article", new {artId = @art.ID}, null)
                @Html.Raw(" | ")
                @Html.ActionLink("Usuń", "DeleteArticle", "Article", new {artId = @art.ID}, null)
            }
            <br/>
            if (art.Content != null)
            {
                <span class="lead">
                    @art.Content
                </span>
            }
            <br/>
            if ( !String.IsNullOrEmpty(art.Image) )
            {
                <a class="group3" href="@Url.Content(art.Image)" title="@art.Content">
                    <img class="img-thumbnail" src="@Url.Content(art.Image)" alt="Image" height="100" width="100"/>
                </a>
            }
            <br/>
            @Html.Raw("</div>")
            @Html.Raw("<div class=\"panel-footer\">")
            @Html.Raw("<b>Komentarze: </b>")
            <br/>

            var comments = new PortalSpolecznosciowy.Repository.GetComments(@art.ID).Comments;
            foreach (var com in comments)
            {
                @Html.Raw("<div class=\"panel-footer\">")
                var author = new PortalSpolecznosciowy.Repository.GetUser(@com.Users_ID).UserLogin;
                <p class="h6">
                    @Html.Raw("<b> autor: " + @author + "</b>")

                    @if (Session["Login"] != null && (new PortalSpolecznosciowy.Repository.GetRole(Session["Login"].ToString()).Role == 2 ||
                                                      new PortalSpolecznosciowy.Repository.GetRole(Session["Login"].ToString()).Role == 3))
                    {
                        //@Html.ActionLink("Edytuj", "EditComment", "Article", new { artId = @art.ID }, null)
                        @Html.ActionLink("Usuń", "DeleteComment", "Article", new {artId = @art.ID, comId = @com.ID}, null)
                    }

                    <br/>
                    <br/>
                    @com.Content
                </p>

                if (com.Image != null)
                {
                    <a class="group3" href="@Url.Content(com.Image)" title="@com.Content">
                        <img class="img-thumbnail" src="@Url.Content(com.Image)" alt="Image" height="100" width="100"/>
                    </a>
                }
                @Html.Raw("</div>")
            }

            @Html.Raw("<div class=\"panel-footer \">")
            @Html.ActionLink("Pokaż wszystkie komentarze", "Index", "Article", new {articleId = art.ID}, null)
            <br/>

            using (Html.BeginForm("AddComment", "MainPanel", FormMethod.Post, new {enctype = "multipart/form-data", id = "Form" + @art.ID}))
            {
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.TextBoxFor(x => x.CommentContent, new {@class = "form-control", id = "Comment" + @art.ID, @Value = "napisz komentarz", onclick = "clearField(this.id)"})
                <br/>
                @Html.TextBoxFor(x => x.File, new {type = "file", id = "CommentFile" + @art.ID, @class = "filestyle", data_input = "false", data_buttonText = "Wybierz obrazek"})
                @Html.Hidden("articleId", @art.ID)
                @Html.Hidden("accessible", 1)
                <br/>
                <input type="submit" value="Skomentuj" onclick="onSend(@art.ID)" class="btn btn-primary"/>
            }
            @Html.Raw("</div>")
            @Html.Raw("</div>")
            @Html.Raw("</div>")
        }

        <div class="btn-groupp pull-right">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("UserProfile", "Users", new {userLogin = @Model.UserLogin, page = x, option = TempData["option"]}))
        </div>

    </div>

    <div class="col-md-4">
        @Html.Partial("Users/_DisplayUserContacts", @Model.UserContacts)
    </div>

</div>

<script>
            var click = false;

            function clearField(id) {
                console.log(id);
                document.getElementById(id).value = "";
                click = true;
            }

            function onSend(formId) {
                if (click == false)
                    document.getElementById("Comment" + formId).value = null;
            }
</script>