PortalSpolecznosciowy/Controllers/MainPanelController.cs
using System;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Models;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    public class MainPanelController : Controller
    {
        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();

        public int PageSize = 10;

        [SessionExistFilter]
        public ActionResult Index(int page = 1, int option = 1)
        {
            string sessionLogin = Session["Login"].ToString();
            int userId = DB.Users.Single(x => x.Login == sessionLogin).ID;
            ProfilAndWall PaW = new ProfilAndWall();

            PaW.user = DB.Users.Single(c => c.Login == sessionLogin);

            if (option == 2) //pokaz moje wpisy
            {
                PaW.articles = DB.Articles
                    //.Where(x => x.Users_ID == userId)
                    .Where(x => x.Users_ID == PaW.user.ID)
                    .OrderByDescending(art => art.Date)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize);

                PaW.PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = DB.Articles.Count()
                };
            }
            else if (option == 1) // pokaz wpisy wszystich innych
            {
                PaW.user = DB.Users.Single(c => c.ID == userId);

                PaW.articles = DB.Articles
                    //.Where(x => x.Users_ID == userId)
                    .Where(x => x.Users_ID != PaW.user.ID)
                    .OrderByDescending(art => art.Date)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize);

                PaW.PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = DB.Articles.Count()
                };
            }
            else if (option == 3) // pokaz wpisy i moje i wszystich innych
            {
                PaW.articles = DB.Articles
                    .OrderByDescending(art => art.Date)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize);

                PaW.PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = DB.Articles.Count()
                };
            }

            int myId = DB.Users.Single(x => x.Login == sessionLogin).ID;
            PaW.Contacts = DB.Contacts.Where(x => x.UserId1 == myId || x.UserId2 == myId).OrderBy(x => x.Active).ToList();

            TempData["option"] = option;
            return View(PaW);
        }

        [HttpPost]
        [SessionExistFilter]
        public ActionResult AddArticle(ProfilAndWall article)
        {
            string userLogin = Session["Login"].ToString();
            if (article.ArticleContent == null && article.File == null)
            {
                TempData["error"] = "Musisz coś wpisać lub dodać obrazek";
                return RedirectToAction("Index");
            }

            Articles art = new Articles
            {
                Users_ID = DB.Users.Single(x => x.Login == userLogin).ID,
                Content = article.ArticleContent,
                Date = DateTime.Now,
                Accessible = 1,
                Image = null
            };

            DB.Articles.Add(art);
            DB.SaveChanges();
            
            if (article.File != null && article.File.ContentLength > 0)
            {
                try
                {
                    string extension = Path.GetExtension(article.File.FileName).ToLower();
                    if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                    {
                        Image image = Image.FromStream(article.File.InputStream, true, true);
                        string path = @"~/ArticleImages/" + art.ID + ".jpeg";
                        image.Save(Server.MapPath(path), System.Drawing.Imaging.ImageFormat.Jpeg);
                        art.Image = path;
                        DB.Articles.AddOrUpdate(art);
                        DB.SaveChanges();
                    }
                    else
                    {
                        throw new Exception("To nie jest obrazek!");
                    }
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Błąd: " + ex.Message;
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [SessionExistFilter]
        public ActionResult AddComment(ProfilAndWall paw, int articleId, int accessible)
        {
            Uri url = null;
            if (paw.user == null)
            {
                paw.user = new Users()
                {
                    Login = Session["Login"].ToString()
                };
                url = Request.UrlReferrer;
            }

            if (paw.CommentContent == null && paw.File == null)
            {
                TempData["error"] = "Musisz napisać komentarz lub dodać obrazek";
                return RedirectToAction("Index");
            }

            Comments com = new Comments
            {
                Users_ID = DB.Users.Single(x => x.Login == paw.user.Login).ID,
                Article_ID = articleId,
                Date = DateTime.Now,
                Accessible = accessible,
                Content = paw.CommentContent,
                Image = null,
            };

            DB.Comments.Add(com);
            DB.SaveChanges();

            if (paw.File != null && paw.File.ContentLength > 0)
            {
                try
                {
                    string extension = Path.GetExtension(paw.File.FileName).ToLower();
                    if (extension == ".jpg" || extension == ".jpeg" || extension == ".png")
                    {
                        Image image = Image.FromStream(paw.File.InputStream, true, true);
                        string path = @"~/CommentImages/" + com.ID + ".jpeg";
                        image.Save(Server.MapPath(path), System.Drawing.Imaging.ImageFormat.Jpeg);
                        com.Image = path;
                        DB.Comments.AddOrUpdate(com);
                        DB.SaveChanges();
                    }
                    else
                    {
                        throw new Exception("To nie jest obrazek!");
                    }
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Błąd: " + ex.Message;
                    return RedirectToAction("Index");
                }
            }

            if(url != null)
                return Redirect(url.ToString());
            else
                return RedirectToAction("Index");
        }

        [SessionExistFilter]
        public ActionResult EditProfile()
        {
            var userLogin = Session["Login"].ToString();

            UserEdit userEdit = new UserEdit
            {
                UserLogin = userLogin,
                ProfileImageUrl = DB.Users.Single(x => x.Login == userLogin).Profil_image
            };

            TempData["UserEmail"] = DB.Users.Single(x => x.Login == userLogin).Email;

            return View(userEdit);
        }
        
    }
}

PortalSpolecznosciowy/Views/MainPanel/EditProfile.cshtml
@model PortalSpolecznosciowy.Models.UserEdit

@{
    ViewBag.Title = "Edytuj profil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj swój profil</h2>
<br />
<br />

<div class="form-group">
    @Html.LabelFor(model => model.UserLogin, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DisplayFor(model => model.UserLogin, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.UserLogin, "", new { @class = "text-danger" })
    </div>
</div>
<br />

@using (Html.BeginForm("ChangeProfileImage", "Login", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @if (TempData["MessageProfileImage"] != null)
                {
                <div class="@TempData["MessageProfileImageOption"]" role="alert">
                    @TempData["MessageProfileImage"]
                </div>
            }
            <p>Zmień Zdjęcie profilowe:</p>
            <div class="col-md-2">
                <a class="group3" href="@Url.Content(@Model.ProfileImageUrl)" title="@Model.UserLogin">
                    <img class="img-thumbnail" src="@Url.Content(@Model.ProfileImageUrl)" alt="Image" height="100" width="100" />
                </a>
            </div>
            @Html.TextBoxFor(x => x.NewProfileImage, new { type = "file", @class = "filestyle", data_input = "false", data_buttonText = "Wybierz obrazek" })
        </div>
        @Html.HiddenFor(x => x.UserLogin, new { @value = @Model.UserLogin })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zmień" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("ChangePassword", "Login", FormMethod.Post, new { id = "changePasswordForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @if (TempData["MessageChangePassword"] != null)
            {
                <div class="@TempData["MessageChangePasswordOption"]" role="alert">
                    @TempData["MessageChangePassword"]
                </div>
            }
            <p>Zmień hasło:</p>
            @Html.LabelFor(model => model.OldPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(x => x.UserLogin, new { @value = @Model.UserLogin })
        @Html.HiddenFor(x => x.PasswordHash, new { id = "PassHash" })
        @Html.HiddenFor(x => x.Ip)
        @Html.HiddenFor(x => x.Token)
        @Html.HiddenFor(x => x.PassHashToken)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Zmień" id="change" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("ChangeEmail", "Login"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @if (TempData["MessageChangeEmail"] != null)
                {
                <div class="@TempData["MessageChangeEmailOption"]" role="alert">
                    @TempData["MessageChangeEmail"]
                </div>
            }
            <p>Zmień email:</p>
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Raw(TempData["UserEmail"].ToString())
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(x => x.UserLogin, new { @value = @Model.UserLogin })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zmień" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/ChangePassword.js"></script>
<script src="~/Scripts/jquery.sha256.min.js"></script>

PortalSpolecznosciowy/Views/MainPanel/Index.cshtml
@model PortalSpolecznosciowy.Models.ProfilAndWall

@{
    ViewBag.Title = "Strona główna";
}

<div class="row panel" style="margin-top:50px;">
    <div class="col-md-3">
        @Html.Partial("MainPage/_Menu", Model.user)
        <br/>
        <br/>
        <br/>
        @Html.Partial("MainPage/_Chat")
    </div>
    <div id="categories" class="col-md-5">

        @if (TempData["error"] != null)
        {
            <div class="text-danger">@TempData["error"]</div>
        }

        @Html.Raw("<b>Napisz artykuł: </b>")
        <br />

        @using (Html.BeginForm("AddArticle", "MainPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.TextAreaFor(x => x.ArticleContent, new { @class = "form-control", @style = "height: 100px; min-width: 99%", @Value = "napisz komentarz", onclick = "clearField(this.id)" })
            <br />
            @Html.TextBoxFor(x => x.File, new { type = "file", @class = "filestyle", data_input = "false", data_buttonText = "Wybierz obrazek" })
            @Html.HiddenFor(x => x.user.Login, new { @value = Session["Login"] })
            <input type="submit" value="Napisz" class="btn btn-primary" style="margin-left: 370px; margin-top: -60px" />
        }

        <br />
        @Html.Partial("MainPage/_Wall")
    </div>

    <div class="col-md-4">
        @Html.Partial("MainPage/_DisplayContacts", @Model.Contacts)
    </div>

    

</div>