PortalSpolecznosciowy/Controllers/AdminPanelController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PortalSpolecznosciowy.FilterContext;
using PortalSpolecznosciowy.Repository;

namespace PortalSpolecznosciowy.Controllers
{
    [Admin]
    [SessionExistFilter]
    public class AdminPanelController : Controller
    {
        private PortalSpolecznosciowyLocalEntities DB = new PortalSpolecznosciowyLocalEntities();

        public ActionResult Index()
        {
            IEnumerable<Users> users = DB.Users.ToList();
            return View(users);
        }

        public ActionResult ChangeRole(string userLogin, int role)
        {
            Users user = DB.Users.Single(x => x.Login == userLogin);
            user.Role = role;
            DB.SaveChanges();
            TempData["Message"] = "uprawnienia zmienione dla użytkownika " + userLogin;
            return RedirectToAction("Index");
        }

        public ActionResult BanUser(string userLogin)
        {
            Users user = DB.Users.Single(x => x.Login == userLogin);
            user.Banned = true;
            DB.SaveChanges();
            TempData["Message"] = "Użytkownik " + userLogin + " został zbanowany!";
            return RedirectToAction("Index");
        }

        public ActionResult UnBanUser(string userLogin)
        {
            Users user = DB.Users.Single(x => x.Login == userLogin);
            user.Banned = false;
            DB.SaveChanges();
            TempData["Message"] = "Użytkownik " + userLogin + " został odbanowany!";
            return RedirectToAction("Index");
        }

        public ActionResult DeleteUser(string userLogin)
        {
            Users user = DB.Users.Single(x => x.Login == userLogin);

            List<Contacts> contactsList = DB.Contacts.Where(x => x.UserId1 == user.ID || x.UserId2 == user.ID).ToList();
            DB.Contacts.RemoveRange(contactsList);
            
            List<Comments> commnetsList = DB.Comments.Where(x => x.Users_ID == user.ID).ToList();
            DB.Comments.RemoveRange(commnetsList);
            
            foreach (var comment in commnetsList)
            {
                string pathToFile = Server.MapPath(comment.Image);
                System.IO.File.Delete(pathToFile);
            }

            List<Articles> articlesesList = DB.Articles.Where(x => x.Users_ID == user.ID).ToList();
            DB.Articles.RemoveRange(articlesesList);

            foreach (var article in articlesesList)
            {
                string pathToFile = Server.MapPath(article.Image);
                System.IO.File.Delete(pathToFile);
            }

            DB.Users.Remove(user);
            DB.SaveChanges();

            TempData["Message"] = "Użytkownik " + userLogin + " został usunięty!";
            return RedirectToAction("Index");
        }


    }
}

PortalSpolecznosciowy/Views/AdminPanel/Index.cshtml
@model IEnumerable<PortalSpolecznosciowy.Repository.Users>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Zarządznie użytkownikami</h2>

@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.LastLoginData)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.LastLoginIP)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "Użytkownik",
                        Value = "1"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Moderator",
                        Value = "2"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Administrator",
                        Value = "3"
                    });

                    using (Html.BeginForm("ChangeRole", "AdminPanel", FormMethod.Post))
                    {
                        @Html.DropDownList("role", new SelectList(listItems, "Value", "Text", @item.Role), new {@class = "btn btn-primary dropdown-toggle", onchange = @"form.submit();"})
                        @Html.Hidden("userLogin", @item.Login)
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.LastLoginData)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.LastLoginIP)
            </td>
            <td>
                @if (item.Banned)
                {
                    @Html.ActionLink("Odbanuj", "UnBanUser", new { userLogin = item.Login })
                    @Html.Raw(" | ")
                }
                else
                {
                    @Html.ActionLink("Banuj", "BanUser", new { userLogin = item.Login })
                    @Html.Raw(" | ")
                }
                @Html.ActionLink("Usuń", "DeleteUser", new { userLogin = item.Login })
            </td>
        </tr>
    }

</table>